name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Mono
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete      

    - name: Download and Install .NET Framework 4.6.2 Developer Pack
      run: |
        wget https://go.microsoft.com/fwlink/?linkid=2099466
        chmod +x ndp462-devpack-kb3151934-enu.exe
        mono ndp462-devpack-kb3151934-enu.exe /quiet /extract:C:\DotNet462
        sudo mkdir -p /opt/dotnet
        sudo mv /DotNet462 /opt/dotnet/ndp462-devpack
        sudo ln -s /opt/dotnet/ndp462-devpack /usr/share/dotnet

    - name: Build
      run: dotnet build -c Release

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./NLOverlay/bin/Release/NLOverlay.exe
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

